version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: cimg/node:current-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
    steps:
      - browser-tools/install-chrome
      - checkout
      - run:
          name: install-dependencies
          command: yarn
      - run:
          name: test
          command: yarn test:ci
      - codecov/upload:
          file: 'coverage/ng-whiteboard/lcov.info'

  demo:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: yarn
      - run: yarn build:demo
      - run: npx angular-cli-ghpages --dir=./dist/demo --repo=https://github.com/mostafazke/ng-whiteboard.git --name="Mostafa Zaki" --email=mmostafazke@gmail.com

  lib:
    docker:
      - image: cimg/node:current-browsers
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: yarn
      - run: yarn build:lib
      - run: yarn publish:lib

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - demo
      - lib:
          filters:
            branches:
              only:
                - master
          context:
            - yarn
          requires:
            - test
